# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    allowed_methods_listener: true

    routing_loader:
        enabled: true
        default_format: json
        include_format: true

    view:
        default_engine: null
        force_redirects: []
        view_response_listener: true
        formats:
            json: true

    format_listener:
        enabled: true
        rules:
            - { path: '^/*', priorities: [ 'json', 'html', '*/*'], fallback_format: 'html' }

    service:
        templating: null

    exception:
        exception_controller: 'fos_rest.exception.controller::showAction'
