nelmio_api_doc:
    documentation:
        info:
            title: Class Plan
            description: A class scheduling utility.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/term
            - ^/[^(_|download|default|doc$)]
