doctrine:
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
            ods:
                connection: ods

    dbal:
        default_connection: default
        connections:
            default:
                url:     '%env(resolve:DATABASE_URL)%'
                driver:  'pdo_mysql'
                charset: UTF8
            ods:
                url:     '%env(resolve:CLASSNAV_DATABASE_URL)%'
                driver:  'pdo_mysql'
                charset: UTF8
