doctrine:
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: false
        entity_managers:
            default:
                connection: default
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool
            ods:
                connection: ods

    dbal:
        default_connection: default
        connections:
            default:
                url:     '%env(resolve:CLASSPLAN_DATABASE_URL)%'
                driver:  'pdo_mysql'
                charset: UTF8
            ods:
                url:     '%env(resolve:CLASSNAV_DATABASE_URL)%'
                driver:  'pdo_mysql'
                charset: UTF8

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
