imports:
    - { resource: "./parameters.yml" }

doctrine:
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        entity_managers:
            default:
                connection: default
            ods:
                connection: ods

    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            ods:
                driver:   pdo_mysql
                host:     "%ods_db_host%"
                port:     "%ods_db_port%"
                dbname:   "%ods_db_name%"
                user:     "%ods_db_user%"
                password: "%ods_db_password%"
                charset:  UTF8

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
